---
before_install:
  - rm -f Gemfile.lock

rvm:
  - "2.0.0"

env:
  - PUPPET_VERSION="~> 4.0.0"

matrix:
  exclude: []

# deploy:
#   provider: puppetforge
#   user: storm49152
#   password:
#     secure: ""
#   on:
#     tags: true
#     # all_branches is required to use tags
#     all_branches: true
#     # Only publish if our main Ruby target builds
#     condition: "$PUPPET_VERSION = '~> 4.0.0'"
